2021-05-25 11:10:54,790 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\Proga\Flask\watch_movie_test\src\__init__.py:74]
2021-05-25 11:10:56,790 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\Proga\Flask\watch_movie_test\src\__init__.py:74]
2021-05-25 13:03:47,751 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\Proga\Flask\heroku-app\heroku\src\__init__.py:74]
2021-05-25 13:03:50,225 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\Proga\Flask\heroku-app\heroku\src\__init__.py:74]
2021-05-25 13:07:43,501 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\Proga\Flask\heroku-app\heroku\src\__init__.py:74]
2021-05-25 15:36:42,128 INFO: Watchmovie startup [in /home/alcoccoque/heroku-app/heroku/src/__init__.py:74]
2021-05-25 15:39:37,485 INFO: Watchmovie startup [in /home/alcoccoque/heroku-app/heroku/src/__init__.py:74]
2021-05-25 15:40:06,109 ERROR: Exception on /movie/result [GET] [in /home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/alcoccoque/heroku-app/heroku/src/main/routes.py", line 70, in result
    title, poster, popularity, genres, overview, vote_average, vote_count, release_date, runtime, \
TypeError: cannot unpack non-iterable NoneType object
2021-05-25 15:41:02,690 ERROR: Exception on /random/result [GET] [in /home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/alcoccoque/heroku-app/heroku/src/main/routes.py", line 72, in result
    return render_template('result.html', title=title, overview=overview, poster=poster,
UnboundLocalError: local variable 'overview' referenced before assignment
2021-05-26 10:29:18,835 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 10:30:08,294 ERROR: Exception on /random/result [GET] [in D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\main\routes.py", line 72, in result
    return render_template('result.html', title=title, overview=overview, poster=poster,
UnboundLocalError: local variable 'overview' referenced before assignment
2021-05-26 10:30:14,604 ERROR: Exception on /movie/result [GET] [in D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\main\routes.py", line 70, in result
    title, poster, popularity, genres, overview, vote_average, vote_count, release_date, runtime, \
TypeError: cannot unpack non-iterable NoneType object
2021-05-26 10:41:49,296 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 10:43:34,306 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 10:44:11,858 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 10:44:30,777 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 10:55:55,136 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 10:56:52,559 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 10:57:25,001 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 12:28:36,456 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 12:29:51,909 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 12:30:14,205 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 13:11:54,140 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 13:13:57,380 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 13:14:32,665 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 13:18:56,712 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 13:23:38,130 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 13:57:08,564 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 14:08:11,745 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 14:08:35,262 ERROR: Exception on /search [GET] [in D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\main\routes.py", line 47, in search
    suggestions = get_suggestions()
  File "C:\Users\Vivo\Desktop\heroku-app\watchmovie\ml\trained_model.py", line 59, in get_suggestions
    data = pd.read_csv('src/ml/main_data.csv')
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'src/ml/main_data.csv'
