2021-05-26 18:14:37,959 ERROR: Exception on /search [GET] [in D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\main\routes.py", line 47, in search
    suggestions = get_suggestions()
  File "C:\Users\Vivo\Desktop\heroku-app\watchmovie\ml\trained_model.py", line 35, in get_suggestions
    return list(data['movie_title'].str.capitalize())
TypeError: string indices must be integers
2021-05-26 18:33:48,384 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 18:33:52,205 ERROR: Exception on /search [GET] [in D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\main\routes.py", line 47, in search
    suggestions = get_suggestions()
  File "C:\Users\Vivo\Desktop\heroku-app\watchmovie\ml\trained_model.py", line 36, in get_suggestions
    return list(data['movie_title'].str.capitalize())
TypeError: string indices must be integers
2021-05-26 18:36:39,451 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 20:13:40,992 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 20:14:35,136 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 20:14:49,261 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 20:38:11,972 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 20:39:45,262 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 21:02:58,076 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 21:03:00,562 ERROR: Exception on /auth/login [GET] [in D:\Programs\Anaconda\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Programs\Anaconda\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Anaconda\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Anaconda\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Anaconda\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\auth\routes.py", line 17, in login
    print(form.remember_me.data)
AttributeError: 'LoginForm' object has no attribute 'remember_me'
2021-05-26 21:03:25,177 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 23:20:36,103 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-27 09:06:03,182 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-27 09:07:13,980 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-27 09:13:54,485 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-27 09:44:49,527 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-27 09:48:30,161 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-27 09:49:16,684 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-27 09:51:34,097 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
