2021-05-25 11:10:54,790 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\Proga\Flask\watch_movie_test\src\__init__.py:74]
2021-05-25 11:10:56,790 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\Proga\Flask\watch_movie_test\src\__init__.py:74]
2021-05-25 13:03:47,751 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\Proga\Flask\heroku-app\heroku\src\__init__.py:74]
2021-05-25 13:03:50,225 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\Proga\Flask\heroku-app\heroku\src\__init__.py:74]
2021-05-25 13:07:43,501 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\Proga\Flask\heroku-app\heroku\src\__init__.py:74]
2021-05-25 15:36:42,128 INFO: Watchmovie startup [in /home/alcoccoque/heroku-app/heroku/src/__init__.py:74]
2021-05-25 15:39:37,485 INFO: Watchmovie startup [in /home/alcoccoque/heroku-app/heroku/src/__init__.py:74]
2021-05-25 15:40:06,109 ERROR: Exception on /movie/result [GET] [in /home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/alcoccoque/heroku-app/heroku/src/main/routes.py", line 70, in result
    title, poster, popularity, genres, overview, vote_average, vote_count, release_date, runtime, \
TypeError: cannot unpack non-iterable NoneType object
2021-05-25 15:41:02,690 ERROR: Exception on /random/result [GET] [in /home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alcoccoque/heroku-app/heroku/env/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/alcoccoque/heroku-app/heroku/src/main/routes.py", line 72, in result
    return render_template('result.html', title=title, overview=overview, poster=poster,
UnboundLocalError: local variable 'overview' referenced before assignment
2021-05-26 10:29:18,835 INFO: Watchmovie startup [in C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\__init__.py:74]
2021-05-26 10:30:08,294 ERROR: Exception on /random/result [GET] [in D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\main\routes.py", line 72, in result
    return render_template('result.html', title=title, overview=overview, poster=poster,
UnboundLocalError: local variable 'overview' referenced before assignment
2021-05-26 10:30:14,604 ERROR: Exception on /movie/result [GET] [in D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Anaconda\envs\watchmovie\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Vivo\Desktop\heroku-app\watchmovie\src\main\routes.py", line 70, in result
    title, poster, popularity, genres, overview, vote_average, vote_count, release_date, runtime, \
TypeError: cannot unpack non-iterable NoneType object
